-- ============================================================================
-- CONTROL F — LOST OBJECT CCTV DETECTION APPLICATION
-- Database: Oracle Database 21c Express Edition (Oracle 21c XE)
-- Schema DDL: Complete Master Tables, Constraints, Indexes, and Triggers
-- ============================================================================

-- Clean up existing objects if re-running (safe drop)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DETECTIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SEARCHES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CAMERAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ============================================================================
-- 1. USERS TABLE
-- Stores authenticated operators, administrators, and general users.
-- ============================================================================
CREATE TABLE USERS (
    USER_ID                 NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    USERNAME                VARCHAR2(50) NOT NULL,
    EMAIL                   VARCHAR2(255) NOT NULL,
    PASSWORD_HASH           VARCHAR2(255) NOT NULL,
    FULL_NAME               VARCHAR2(150),
    ROLE                    VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    IS_ACTIVE               NUMBER(1) DEFAULT 1 NOT NULL,
    REFRESH_TOKEN_HASH      VARCHAR2(255),
    FAILED_LOGIN_ATTEMPTS   NUMBER DEFAULT 0 NOT NULL,
    LOCKED_UNTIL            TIMESTAMP WITH TIME ZONE,
    LAST_LOGIN              TIMESTAMP WITH TIME ZONE,
    CREATED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN ('ADMIN', 'USER', 'OPERATOR')),
    CONSTRAINT CK_USERS_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

-- Trigger to maintain UPDATED_AT on USERS
CREATE OR REPLACE TRIGGER TRG_USERS_UPDATED_AT
BEFORE UPDATE ON USERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- ============================================================================
-- 2. CAMERAS TABLE
-- Stores CCTV camera definitions, video sources, physical locations, and status.
-- ============================================================================
CREATE TABLE CAMERAS (
    CAMERA_ID               NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CAMERA_NAME             VARCHAR2(100) NOT NULL,
    CAMERA_LOCATION         VARCHAR2(150) NOT NULL,
    CAMERA_SOURCE           VARCHAR2(500) NOT NULL,
    STATUS                  VARCHAR2(20) DEFAULT 'OFFLINE' NOT NULL,
    CREATED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CAMERAS PRIMARY KEY (CAMERA_ID),
    CONSTRAINT CK_CAMERAS_STATUS CHECK (STATUS IN ('ONLINE', 'OFFLINE', 'PROCESSING'))
);

-- Trigger to maintain UPDATED_AT on CAMERAS
CREATE OR REPLACE TRIGGER TRG_CAMERAS_UPDATED_AT
BEFORE UPDATE ON CAMERAS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- ============================================================================
-- 3. SEARCHES TABLE
-- Tracks each object search session initiated by users across CCTV cameras or videos.
-- ============================================================================
CREATE TABLE SEARCHES (
    SEARCH_ID               NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    USER_ID                 NUMBER NOT NULL,
    OBJECT_NAME             VARCHAR2(100) NOT NULL,
    CAMERA_ID               NUMBER,
    SEARCH_STATUS           VARCHAR2(20) DEFAULT 'PROCESSING' NOT NULL,
    STARTED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT            TIMESTAMP WITH TIME ZONE,
    CREATED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SEARCHES PRIMARY KEY (SEARCH_ID),
    CONSTRAINT FK_SEARCHES_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SEARCHES_CAMERA FOREIGN KEY (CAMERA_ID)
        REFERENCES CAMERAS (CAMERA_ID) ON DELETE SET NULL,
    CONSTRAINT CK_SEARCHES_STATUS CHECK (SEARCH_STATUS IN ('PROCESSING', 'FOUND', 'NOT_FOUND', 'FAILED'))
);

-- ============================================================================
-- 4. DETECTIONS TABLE
-- Contains verified detection events with the EXACT captured frame stored as a BLOB.
-- ============================================================================
CREATE TABLE DETECTIONS (
    DETECTION_ID            NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    USER_ID                 NUMBER NOT NULL,
    SEARCH_ID               NUMBER NOT NULL,
    CAMERA_ID               NUMBER,
    OBJECT_NAME             VARCHAR2(100) NOT NULL,
    CONFIDENCE              NUMBER(5, 2) NOT NULL,
    TIMESTAMP_SECONDS       NUMBER(10, 3) NOT NULL,
    VIDEO_TIMESTAMP         VARCHAR2(20) NOT NULL,
    FRAME_NUMBER            NUMBER NOT NULL,
    BOUNDING_BOX_X          NUMBER(10, 2) NOT NULL,
    BOUNDING_BOX_Y          NUMBER(10, 2) NOT NULL,
    BOUNDING_BOX_WIDTH      NUMBER(10, 2) NOT NULL,
    BOUNDING_BOX_HEIGHT     NUMBER(10, 2) NOT NULL,
    DETECTION_STATUS        VARCHAR2(50) DEFAULT 'ACQUIRED' NOT NULL,
    DETECTION_IMAGE         BLOB,
    CREATED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DETECTIONS PRIMARY KEY (DETECTION_ID),
    CONSTRAINT FK_DETECTIONS_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_DETECTIONS_SEARCH FOREIGN KEY (SEARCH_ID)
        REFERENCES SEARCHES (SEARCH_ID) ON DELETE CASCADE,
    CONSTRAINT FK_DETECTIONS_CAMERA FOREIGN KEY (CAMERA_ID)
        REFERENCES CAMERAS (CAMERA_ID) ON DELETE SET NULL,
    CONSTRAINT CK_DETECTIONS_CONF CHECK (CONFIDENCE BETWEEN 0 AND 100),
    CONSTRAINT CK_DETECTIONS_FRAME CHECK (FRAME_NUMBER >= 0)
);

-- ============================================================================
-- PERFORMANCE & LOOKUP INDEXES
-- ============================================================================
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_USERS_USERNAME ON USERS(USERNAME);
CREATE INDEX IDX_CAMERAS_STATUS ON CAMERAS(STATUS);
CREATE INDEX IDX_SEARCHES_USER_ID ON SEARCHES(USER_ID);
CREATE INDEX IDX_SEARCHES_STATUS ON SEARCHES(SEARCH_STATUS);
CREATE INDEX IDX_SEARCHES_CAMERA_ID ON SEARCHES(CAMERA_ID);
CREATE INDEX IDX_DETECTIONS_SEARCH_ID ON DETECTIONS(SEARCH_ID);
CREATE INDEX IDX_DETECTIONS_CAMERA_ID ON DETECTIONS(CAMERA_ID);
CREATE INDEX IDX_DETECTIONS_USER_ID ON DETECTIONS(USER_ID);
CREATE INDEX IDX_DETECTIONS_OBJECT ON DETECTIONS(OBJECT_NAME);
CREATE INDEX IDX_DETECTIONS_FRAME ON DETECTIONS(FRAME_NUMBER);

-- Commit transaction
COMMIT;
