-- ============================================================================
-- Migration 001: Create APP_USERS
-- System: CONTROL F — AI Object Detection & Recovery System
-- Database: Oracle Database 21c XE
-- ============================================================================

CREATE TABLE APP_USERS (
    USER_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    FULL_NAME       VARCHAR2(150) NOT NULL,
    EMAIL           VARCHAR2(255) NOT NULL,
    PASSWORD_HASH   VARCHAR2(255) NOT NULL,
    ROLE            VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_LOGIN_AT   TIMESTAMP WITH TIME ZONE,
    -- Primary Key Constraint
    CONSTRAINT PK_APP_USERS PRIMARY KEY (USER_ID),
    -- Business Domain & Security Constraints
    CONSTRAINT UQ_APP_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_APP_USERS_ROLE CHECK (ROLE IN ('USER', 'ADMIN')),
    CONSTRAINT CK_APP_USERS_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_APP_USERS_EMAIL_FMT CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'))
);

-- Comments for Data Dictionary Documentation
COMMENT ON TABLE APP_USERS IS 'Authentication, identity, and security roles for application operators and administrators.';
COMMENT ON COLUMN APP_USERS.USER_ID IS 'Surrogate primary key auto-generated via 21c identity column.';
COMMENT ON COLUMN APP_USERS.EMAIL IS 'Normalized unique email address for operator identification.';
COMMENT ON COLUMN APP_USERS.PASSWORD_HASH IS 'Bcrypt salted password digest (work factor >= 12).';
COMMENT ON COLUMN APP_USERS.ROLE IS 'Access control role: USER or ADMIN.';
COMMENT ON COLUMN APP_USERS.STATUS IS 'Account status lifecycle: ACTIVE or DISABLED.';
COMMENT ON COLUMN APP_USERS.LAST_LOGIN_AT IS 'Timestamp with time zone of most recent successful authentication.';

-- Auto-update trigger for UPDATED_AT column
CREATE OR REPLACE TRIGGER TRG_APP_USERS_UPDATED_AT
BEFORE UPDATE ON APP_USERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/
