-- ============================================================================
-- Migration 002: Create USER_SESSIONS
-- System: CONTROL F — AI Object Detection & Recovery System
-- Database: Oracle Database 21c XE
-- ============================================================================

CREATE TABLE USER_SESSIONS (
    SESSION_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    USER_ID             NUMBER NOT NULL,
    REFRESH_TOKEN_HASH  VARCHAR2(255) NOT NULL,
    EXPIRES_AT          TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    REVOKED_AT          TIMESTAMP WITH TIME ZONE,
    IP_ADDRESS          VARCHAR2(45),
    USER_AGENT          VARCHAR2(500),
    -- Primary Key Constraint
    CONSTRAINT PK_USER_SESSIONS PRIMARY KEY (SESSION_ID),
    -- Referential Integrity: Cascade session destruction on user deletion
    CONSTRAINT FK_USER_SESSIONS_USER FOREIGN KEY (USER_ID)
        REFERENCES APP_USERS (USER_ID) ON DELETE CASCADE,
    -- Constraints
    CONSTRAINT UQ_USER_SESSIONS_TOKEN UNIQUE (REFRESH_TOKEN_HASH),
    CONSTRAINT CK_USER_SESSIONS_EXP CHECK (EXPIRES_AT > CREATED_AT)
);

COMMENT ON TABLE USER_SESSIONS IS 'Active and historical refresh token sessions for stateful JWT revocation.';
COMMENT ON COLUMN USER_SESSIONS.SESSION_ID IS 'Surrogate primary key auto-generated via identity column.';
COMMENT ON COLUMN USER_SESSIONS.USER_ID IS 'Foreign key reference to authenticated APP_USERS.';
COMMENT ON COLUMN USER_SESSIONS.REFRESH_TOKEN_HASH IS 'Cryptographic SHA-256 hash of issued refresh token.';
COMMENT ON COLUMN USER_SESSIONS.EXPIRES_AT IS 'Timestamp when the session token expires.';
COMMENT ON COLUMN USER_SESSIONS.REVOKED_AT IS 'Timestamp when the token was explicitly revoked/logged out.';
