-- ============================================================================
-- Migration 003: Create CAMERAS
-- System: CONTROL F — AI Object Detection & Recovery System
-- Database: Oracle Database 21c XE
-- ============================================================================

CREATE TABLE CAMERAS (
    CAMERA_ID           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    USER_ID             NUMBER NOT NULL,
    CAMERA_NAME         VARCHAR2(100) NOT NULL,
    LOCATION_NAME       VARCHAR2(150) NOT NULL,
    STREAM_URL          VARCHAR2(500) NOT NULL,
    ENCRYPTED_USERNAME  VARCHAR2(255),
    ENCRYPTED_PASSWORD  VARCHAR2(255),
    STATUS              VARCHAR2(20) DEFAULT 'OFFLINE' NOT NULL,
    CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_CONNECTED_AT   TIMESTAMP WITH TIME ZONE,
    -- Primary Key Constraint
    CONSTRAINT PK_CAMERAS PRIMARY KEY (CAMERA_ID),
    -- Referential Integrity: Cascade deletion when owner user is purged
    CONSTRAINT FK_CAMERAS_USER FOREIGN KEY (USER_ID)
        REFERENCES APP_USERS (USER_ID) ON DELETE CASCADE,
    -- Domain Check Constraints
    CONSTRAINT CK_CAMERAS_STATUS CHECK (STATUS IN ('ONLINE', 'OFFLINE', 'ERROR', 'DISABLED')),
    CONSTRAINT CK_CAMERAS_URL CHECK (
        STREAM_URL LIKE 'rtsp://%' OR 
        STREAM_URL LIKE 'rtsps://%' OR 
        STREAM_URL LIKE 'http://%' OR 
        STREAM_URL LIKE 'https://%'
    )
);

COMMENT ON TABLE CAMERAS IS 'Registered CCTV and IP surveillance cameras ingested for AI object searches.';
COMMENT ON COLUMN CAMERAS.CAMERA_ID IS 'Surrogate primary key auto-generated via identity column.';
COMMENT ON COLUMN CAMERAS.USER_ID IS 'Foreign key reference to camera owner in APP_USERS.';
COMMENT ON COLUMN CAMERAS.CAMERA_NAME IS 'Human-readable identifier (e.g. North Gate Entrance Cam).';
COMMENT ON COLUMN CAMERAS.LOCATION_NAME IS 'Physical location context (e.g. Building B Floor 2 Corridor).';
COMMENT ON COLUMN CAMERAS.STREAM_URL IS 'RTSP or HLS video network stream endpoint.';
COMMENT ON COLUMN CAMERAS.ENCRYPTED_USERNAME IS 'AES-256-GCM encrypted camera auth username.';
COMMENT ON COLUMN CAMERAS.ENCRYPTED_PASSWORD IS 'AES-256-GCM encrypted camera auth password.';
COMMENT ON COLUMN CAMERAS.STATUS IS 'Health status: ONLINE, OFFLINE, ERROR, or DISABLED.';

-- Auto-update trigger for UPDATED_AT column
CREATE OR REPLACE TRIGGER TRG_CAMERAS_UPDATED_AT
BEFORE UPDATE ON CAMERAS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/
