-- ============================================================================
-- Migration 004: Create VIDEO_FILES
-- System: CONTROL F — AI Object Detection & Recovery System
-- Database: Oracle Database 21c XE
-- ============================================================================

CREATE TABLE VIDEO_FILES (
    VIDEO_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    USER_ID             NUMBER NOT NULL,
    ORIGINAL_FILENAME   VARCHAR2(255) NOT NULL,
    STORED_FILENAME     VARCHAR2(255) NOT NULL,
    FILE_PATH           VARCHAR2(500) NOT NULL,
    MIME_TYPE           VARCHAR2(100) NOT NULL,
    FILE_SIZE           NUMBER NOT NULL,
    DURATION_SECONDS    NUMBER(10, 2),
    WIDTH               NUMBER(5),
    HEIGHT              NUMBER(5),
    FPS                 NUMBER(6, 2),
    STATUS              VARCHAR2(20) DEFAULT 'READY' NOT NULL,
    UPLOADED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    -- Primary Key Constraint
    CONSTRAINT PK_VIDEO_FILES PRIMARY KEY (VIDEO_ID),
    -- Referential Integrity: Cascade on user deletion
    CONSTRAINT FK_VIDEO_FILES_USER FOREIGN KEY (USER_ID)
        REFERENCES APP_USERS (USER_ID) ON DELETE CASCADE,
    -- Unique constraint on system stored UUID filename
    CONSTRAINT UQ_VIDEO_FILES_STORED UNIQUE (STORED_FILENAME),
    -- Domain Check Constraints
    CONSTRAINT CK_VIDEO_FILES_STATUS CHECK (STATUS IN ('READY', 'PROCESSING', 'FAILED')),
    CONSTRAINT CK_VIDEO_FILES_SIZE CHECK (FILE_SIZE > 0),
    CONSTRAINT CK_VIDEO_FILES_MIME CHECK (
        MIME_TYPE IN ('video/mp4', 'video/quicktime', 'video/x-msvideo', 'video/x-matroska', 'video/webm')
    )
);

COMMENT ON TABLE VIDEO_FILES IS 'Uploaded surveillance video clips and evidence recordings for AI search.';
COMMENT ON COLUMN VIDEO_FILES.VIDEO_ID IS 'Surrogate primary key auto-generated via identity column.';
COMMENT ON COLUMN VIDEO_FILES.USER_ID IS 'Foreign key reference to uploading user in APP_USERS.';
COMMENT ON COLUMN VIDEO_FILES.ORIGINAL_FILENAME IS 'Original filename uploaded by client (sanitized).';
COMMENT ON COLUMN VIDEO_FILES.STORED_FILENAME IS 'Server-generated collision-resistant UUID filename.';
COMMENT ON COLUMN VIDEO_FILES.FILE_PATH IS 'Absolute or relative disk/object storage path.';
COMMENT ON COLUMN VIDEO_FILES.FILE_SIZE IS 'File size in bytes.';
COMMENT ON COLUMN VIDEO_FILES.FPS IS 'Frames per second derived from FFmpeg inspection.';
