-- ============================================================================
-- Migration 005: Create OBJECT_QUERIES
-- System: CONTROL F — AI Object Detection & Recovery System
-- Database: Oracle Database 21c XE
-- ============================================================================

CREATE TABLE OBJECT_QUERIES (
    QUERY_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    USER_ID             NUMBER NOT NULL,
    OBJECT_NAME         VARCHAR2(100) NOT NULL,
    OBJECT_DESCRIPTION  VARCHAR2(1000),
    CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    -- Primary Key Constraint
    CONSTRAINT PK_OBJECT_QUERIES PRIMARY KEY (QUERY_ID),
    -- Referential Integrity
    CONSTRAINT FK_OBJECT_QUERIES_USER FOREIGN KEY (USER_ID)
        REFERENCES APP_USERS (USER_ID) ON DELETE CASCADE,
    -- Constraints
    CONSTRAINT CK_OBJECT_QUERIES_NAME CHECK (LENGTH(TRIM(OBJECT_NAME)) >= 2)
);

COMMENT ON TABLE OBJECT_QUERIES IS 'Natural language object descriptions and search queries entered by operators.';
COMMENT ON COLUMN OBJECT_QUERIES.QUERY_ID IS 'Surrogate primary key auto-generated via identity column.';
COMMENT ON COLUMN OBJECT_QUERIES.USER_ID IS 'Operator who initiated the object query.';
COMMENT ON COLUMN OBJECT_QUERIES.OBJECT_NAME IS 'Primary target label (e.g. keys, backpack, laptop).';
COMMENT ON COLUMN OBJECT_QUERIES.OBJECT_DESCRIPTION IS 'Descriptive visual attributes (e.g. silver house keys with blue keychain).';
