-- ============================================================================
-- Migration 007: Create SEARCH_EVENTS
-- System: CONTROL F — AI Object Detection & Recovery System
-- Database: Oracle Database 21c XE
-- ============================================================================

CREATE TABLE SEARCH_EVENTS (
    EVENT_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    SEARCH_ID           NUMBER NOT NULL,
    EVENT_TYPE          VARCHAR2(50) NOT NULL,
    MESSAGE             VARCHAR2(1000) NOT NULL,
    PROGRESS_PERCENT    NUMBER(5, 2) NOT NULL,
    EVENT_DATA          JSON,
    CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    -- Primary Key Constraint
    CONSTRAINT PK_SEARCH_EVENTS PRIMARY KEY (EVENT_ID),
    -- Referential Integrity: Cascade on search session purge
    CONSTRAINT FK_SEARCH_EVENTS_SEARCH FOREIGN KEY (SEARCH_ID)
        REFERENCES SEARCH_SESSIONS (SEARCH_ID) ON DELETE CASCADE,
    -- Constraints
    CONSTRAINT CK_SEARCH_EVENTS_PROG CHECK (PROGRESS_PERCENT BETWEEN 0 AND 100)
);

COMMENT ON TABLE SEARCH_EVENTS IS 'Granular execution telemetry and stage milestones streamed to frontend via WebSocket.';
COMMENT ON COLUMN SEARCH_EVENTS.EVENT_ID IS 'Surrogate primary key auto-generated via identity column.';
COMMENT ON COLUMN SEARCH_EVENTS.SEARCH_ID IS 'Foreign key reference to SEARCH_SESSIONS.';
COMMENT ON COLUMN SEARCH_EVENTS.EVENT_TYPE IS 'Stage identifier (e.g. EXTRACTING_FRAMES, CANDIDATE_MATCH, TEMPORAL_VERIFICATION).';
COMMENT ON COLUMN SEARCH_EVENTS.EVENT_DATA IS 'Oracle 21c native JSON payload containing feature vectors and frame stats.';
