-- ============================================================================
-- Migration 009: Create AUDIT_LOGS
-- System: CONTROL F — AI Object Detection & Recovery System
-- Database: Oracle Database 21c XE
-- ============================================================================

CREATE TABLE AUDIT_LOGS (
    AUDIT_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    USER_ID         NUMBER,
    ACTION          VARCHAR2(100) NOT NULL,
    ENTITY_TYPE     VARCHAR2(50) NOT NULL,
    ENTITY_ID       VARCHAR2(100),
    REQUEST_ID      VARCHAR2(100),
    IP_ADDRESS      VARCHAR2(45),
    DETAILS         JSON,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    -- Primary Key Constraint
    CONSTRAINT PK_AUDIT_LOGS PRIMARY KEY (AUDIT_ID),
    -- Preserve Audit History: NEVER CASCADE DELETE AUDIT RECORDS
    CONSTRAINT FK_AUDIT_LOGS_USER FOREIGN KEY (USER_ID)
        REFERENCES APP_USERS (USER_ID) ON DELETE SET NULL,
    -- Constraints
    CONSTRAINT CK_AUDIT_LOGS_ACTION CHECK (LENGTH(TRIM(ACTION)) >= 3)
);

COMMENT ON TABLE AUDIT_LOGS IS 'Immutable regulatory and forensic audit trail for system operations.';
COMMENT ON COLUMN AUDIT_LOGS.AUDIT_ID IS 'Surrogate primary key auto-generated via identity column.';
COMMENT ON COLUMN AUDIT_LOGS.USER_ID IS 'Operator identifier (retained as NULL if user is removed).';
COMMENT ON COLUMN AUDIT_LOGS.ACTION IS 'Action performed (e.g. USER_LOGIN, CAMERA_REGISTERED, SEARCH_INITIATED).';
COMMENT ON COLUMN AUDIT_LOGS.ENTITY_TYPE IS 'Resource category (e.g. USER, CAMERA, VIDEO, SEARCH_SESSION).';
COMMENT ON COLUMN AUDIT_LOGS.REQUEST_ID IS 'Correlation ID tracing across microservices/HTTP requests.';
COMMENT ON COLUMN AUDIT_LOGS.DETAILS IS 'Oracle 21c JSON payload containing contextual non-sensitive telemetry.';
