-- ============================================================================
-- Migration 010: Create Performance & Compound Indexes
-- System: CONTROL F — AI Object Detection & Recovery System
-- Database: Oracle Database 21c XE
-- ============================================================================

-- 1. Identity & Session Performance Indexes
CREATE INDEX IDX_APP_USERS_LOWER_EMAIL 
    ON APP_USERS (LOWER(EMAIL));

CREATE INDEX IDX_USER_SESSIONS_USER_EXP 
    ON USER_SESSIONS (USER_ID, EXPIRES_AT, REVOKED_AT);

-- 2. Camera & Video Ingestion Indexes
CREATE INDEX IDX_CAMERAS_USER_ID 
    ON CAMERAS (USER_ID);

CREATE INDEX IDX_CAMERAS_USER_STATUS 
    ON CAMERAS (USER_ID, STATUS);

CREATE INDEX IDX_VIDEO_FILES_USER_ID 
    ON VIDEO_FILES (USER_ID);

CREATE INDEX IDX_VIDEO_FILES_USER_UPLOAD 
    ON VIDEO_FILES (USER_ID, UPLOADED_AT DESC);

-- 3. Search Sessions & Operational Workflow Indexes
CREATE INDEX IDX_SEARCH_SESSIONS_USER_ID 
    ON SEARCH_SESSIONS (USER_ID);

CREATE INDEX IDX_SEARCH_SESSIONS_STATUS 
    ON SEARCH_SESSIONS (STATUS);

CREATE INDEX IDX_SEARCH_SESSIONS_CREATED 
    ON SEARCH_SESSIONS (CREATED_AT DESC);

-- Compound index for rapid operator dashboard queries
CREATE INDEX IDX_SEARCH_SESSIONS_COMP_DASH 
    ON SEARCH_SESSIONS (USER_ID, STATUS, CREATED_AT DESC);

-- Index for source lookup
CREATE INDEX IDX_SEARCH_SESSIONS_VID 
    ON SEARCH_SESSIONS (VIDEO_ID);

CREATE INDEX IDX_SEARCH_SESSIONS_CAM 
    ON SEARCH_SESSIONS (CAMERA_ID);

-- 4. Search Event Telemetry
CREATE INDEX IDX_SEARCH_EVENTS_SEARCH_ID 
    ON SEARCH_EVENTS (SEARCH_ID);

CREATE INDEX IDX_SEARCH_EVENTS_SEARCH_TIME 
    ON SEARCH_EVENTS (SEARCH_ID, CREATED_AT ASC);

-- 5. Frame Extraction & Detection Results Indexes
CREATE INDEX IDX_DET_FRAMES_SEARCH_NUM 
    ON DETECTION_FRAMES (SEARCH_ID, FRAME_NUMBER);

CREATE INDEX IDX_DETECTION_RESULTS_SEARCH 
    ON DETECTION_RESULTS (SEARCH_ID);

CREATE INDEX IDX_DETECTION_RESULTS_TIME 
    ON DETECTION_RESULTS (DETECTED_AT DESC);

-- Compound index for ranking detections by AI confidence score
CREATE INDEX IDX_DETECTION_RESULTS_SCORE 
    ON DETECTION_RESULTS (SEARCH_ID, CONFIDENCE_SCORE DESC);

-- 6. Audit Trail & Compliance Indexes
CREATE INDEX IDX_AUDIT_LOGS_USER_ID 
    ON AUDIT_LOGS (USER_ID);

CREATE INDEX IDX_AUDIT_LOGS_CREATED 
    ON AUDIT_LOGS (CREATED_AT DESC);

CREATE INDEX IDX_AUDIT_LOGS_ENTITY 
    ON AUDIT_LOGS (ENTITY_TYPE, ENTITY_ID);
