-- ============================================================================
-- Migration 011: Create Analytical & Operational Views
-- System: CONTROL F — AI Object Detection & Recovery System
-- Database: Oracle Database 21c XE
-- ============================================================================

-- 1. Detailed User Search History with Source Resolution
CREATE OR REPLACE VIEW V_USER_SEARCH_HISTORY AS
SELECT 
    s.SEARCH_ID,
    s.USER_ID,
    u.FULL_NAME AS OPERATOR_NAME,
    u.EMAIL AS OPERATOR_EMAIL,
    q.OBJECT_NAME,
    q.OBJECT_DESCRIPTION,
    s.SOURCE_TYPE,
    CASE 
        WHEN s.SOURCE_TYPE = 'VIDEO' THEN v.ORIGINAL_FILENAME
        WHEN s.SOURCE_TYPE = 'CAMERA' THEN c.CAMERA_NAME
        ELSE 'UNKNOWN'
    END AS SOURCE_NAME,
    s.VIDEO_ID,
    s.CAMERA_ID,
    s.STATUS,
    s.PROGRESS_PERCENT,
    s.STARTED_AT,
    s.COMPLETED_AT,
    ROUND(
        (CAST(NVL(s.COMPLETED_AT, SYSTIMESTAMP) AS DATE) - CAST(s.STARTED_AT AS DATE)) * 86400, 
        2
    ) AS DURATION_SECONDS,
    s.ERROR_MESSAGE,
    (SELECT COUNT(*) FROM DETECTION_RESULTS d WHERE d.SEARCH_ID = s.SEARCH_ID) AS DETECTION_COUNT,
    s.CREATED_AT
FROM SEARCH_SESSIONS s
JOIN APP_USERS u ON s.USER_ID = u.USER_ID
JOIN OBJECT_QUERIES q ON s.QUERY_ID = q.QUERY_ID
LEFT JOIN VIDEO_FILES v ON s.VIDEO_ID = v.VIDEO_ID
LEFT JOIN CAMERAS c ON s.CAMERA_ID = c.CAMERA_ID;

COMMENT ON TABLE V_USER_SEARCH_HISTORY IS 'Operational view unifying search sessions, queries, and media source details.';

-- 2. Recent Visual Detections for Incident Investigation
CREATE OR REPLACE VIEW V_RECENT_DETECTIONS AS
SELECT 
    d.DETECTION_ID,
    d.SEARCH_ID,
    s.USER_ID,
    u.FULL_NAME AS OPERATOR_NAME,
    d.OBJECT_NAME,
    d.CONFIDENCE_SCORE,
    ROUND(d.CONFIDENCE_SCORE * 100, 2) AS CONFIDENCE_PERCENT,
    d.CAMERA_ID,
    c.CAMERA_NAME,
    c.LOCATION_NAME AS CAMERA_LOCATION,
    d.VIDEO_ID,
    v.ORIGINAL_FILENAME AS VIDEO_FILENAME,
    d.FRAME_NUMBER,
    d.FRAME_TIMESTAMP_MS,
    ROUND(d.FRAME_TIMESTAMP_MS / 1000, 2) AS FRAME_TIMESTAMP_SECONDS,
    d.BOUNDING_BOX_X,
    d.BOUNDING_BOX_Y,
    d.BOUNDING_BOX_WIDTH,
    d.BOUNDING_BOX_HEIGHT,
    d.IMAGE_PATH AS EVIDENCE_IMAGE_PATH,
    d.VERIFIED,
    d.DETECTED_AT
FROM DETECTION_RESULTS d
JOIN SEARCH_SESSIONS s ON d.SEARCH_ID = s.SEARCH_ID
JOIN APP_USERS u ON s.USER_ID = u.USER_ID
LEFT JOIN CAMERAS c ON d.CAMERA_ID = c.CAMERA_ID
LEFT JOIN VIDEO_FILES v ON d.VIDEO_ID = v.VIDEO_ID;

COMMENT ON TABLE V_RECENT_DETECTIONS IS 'Forensic view of AI positive detections with bounding box geometry.';

-- 3. Camera Health & Operational Telemetry
CREATE OR REPLACE VIEW V_CAMERA_HEALTH AS
SELECT 
    c.CAMERA_ID,
    c.USER_ID,
    u.EMAIL AS OWNER_EMAIL,
    c.CAMERA_NAME,
    c.LOCATION_NAME,
    c.STATUS,
    c.LAST_CONNECTED_AT,
    CASE 
        WHEN c.LAST_CONNECTED_AT IS NULL THEN NULL
        ELSE ROUND((CAST(SYSTIMESTAMP AS DATE) - CAST(c.LAST_CONNECTED_AT AS DATE)) * 1440, 1)
    END AS MINUTES_SINCE_LAST_PING,
    (SELECT COUNT(*) FROM SEARCH_SESSIONS s WHERE s.CAMERA_ID = c.CAMERA_ID) AS TOTAL_SEARCHES_RUN,
    (SELECT COUNT(*) FROM DETECTION_RESULTS d WHERE d.CAMERA_ID = c.CAMERA_ID) AS TOTAL_OBJECTS_DETECTED,
    c.CREATED_AT
FROM CAMERAS c
JOIN APP_USERS u ON c.USER_ID = u.USER_ID;

COMMENT ON TABLE V_CAMERA_HEALTH IS 'Diagnostic view tracking camera stream availability and detection volume.';

-- 4. High-Level AI Search Performance Summary
CREATE OR REPLACE VIEW V_SEARCH_SUMMARY AS
SELECT 
    s.STATUS,
    s.SOURCE_TYPE,
    COUNT(*) AS TOTAL_SESSIONS,
    ROUND(AVG(s.PROGRESS_PERCENT), 1) AS AVG_PROGRESS,
    ROUND(
        AVG(
            CASE 
                WHEN s.COMPLETED_AT IS NOT NULL 
                THEN (CAST(s.COMPLETED_AT AS DATE) - CAST(s.STARTED_AT AS DATE)) * 86400 
                ELSE NULL 
            END
        ), 
        2
    ) AS AVG_EXECUTION_SECONDS,
    SUM(CASE WHEN d.DETECTION_ID IS NOT NULL THEN 1 ELSE 0 END) AS POSITIVE_DETECTIONS
FROM SEARCH_SESSIONS s
LEFT JOIN DETECTION_RESULTS d ON s.SEARCH_ID = d.SEARCH_ID
GROUP BY s.STATUS, s.SOURCE_TYPE;

COMMENT ON TABLE V_SEARCH_SUMMARY IS 'System aggregate metrics grouped by pipeline lifecycle stage and source.';
