-- Phase 8: Real Live CCTV / RTSP Streaming Integration Schema Extensions
-- Authoritative tables for real-time camera streaming, stream health telemetry, and per-camera search jobs

-- 1. Extend CAMERAS table with stream configuration fields
ALTER TABLE CAMERAS ADD (
    SOURCE_TYPE VARCHAR2(30) DEFAULT 'RTSP',
    SOURCE_URI_ENCRYPTED VARCHAR2(1000) NULL,
    ENABLED NUMBER(1) DEFAULT 1,
    PRIORITY NUMBER(3) DEFAULT 1,
    CALIBRATION_ID VARCHAR2(36) NULL
);

-- 2. CAMERA_STREAM_STATUS: Authoritative real-time stream metrics and lifecycle state
CREATE TABLE CAMERA_STREAM_STATUS (
    CAMERA_ID VARCHAR2(50) PRIMARY KEY,
    STATUS VARCHAR2(30) DEFAULT 'STOPPED' NOT NULL,
    CONNECTED_AT TIMESTAMP WITH TIME ZONE NULL,
    LAST_FRAME_AT TIMESTAMP WITH TIME ZONE NULL,
    LAST_ERROR VARCHAR2(500) NULL,
    CURRENT_FPS NUMBER(5, 2) DEFAULT 0.0,
    FRAMES_RECEIVED NUMBER(10) DEFAULT 0,
    FRAMES_DROPPED NUMBER(10) DEFAULT 0,
    RECONNECT_ATTEMPTS NUMBER(5) DEFAULT 0,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_STREAM_STATUS_CAMERA FOREIGN KEY (CAMERA_ID) REFERENCES CAMERAS(ID) ON DELETE CASCADE
);

-- 3. SEARCH_JOBS: Per-camera search execution tracking in multi-camera live orchestrations
CREATE TABLE SEARCH_JOBS (
    ID VARCHAR2(36) PRIMARY KEY,
    SESSION_ID VARCHAR2(36) NOT NULL,
    CAMERA_ID VARCHAR2(50) NOT NULL,
    JOB_STATUS VARCHAR2(30) DEFAULT 'QUEUED' NOT NULL,
    STARTED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ENDED_AT TIMESTAMP WITH TIME ZONE NULL,
    FRAMES_PROCESSED NUMBER(10) DEFAULT 0,
    LAST_FRAME_AT TIMESTAMP WITH TIME ZONE NULL,
    ERROR_MESSAGE VARCHAR2(500) NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_SEARCH_JOB_SESSION FOREIGN KEY (SESSION_ID) REFERENCES SEARCH_SESSIONS(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_SEARCH_JOBS_SESSION ON SEARCH_JOBS(SESSION_ID);
CREATE INDEX IDX_SEARCH_JOBS_CAMERA ON SEARCH_JOBS(CAMERA_ID);

-- 4. CAMERA_EVENTS: Audit log of camera streaming lifecycle events
CREATE TABLE CAMERA_EVENTS (
    ID VARCHAR2(36) PRIMARY KEY,
    CAMERA_ID VARCHAR2(50) NOT NULL,
    EVENT_TYPE VARCHAR2(50) NOT NULL,
    EVENT_TIME TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    METADATA VARCHAR2(2000) NULL
);

CREATE INDEX IDX_CAMERA_EVENTS_CAM_TIME ON CAMERA_EVENTS(CAMERA_ID, EVENT_TIME);
