const oracledb = require('oracledb');
const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

const ddl = [
  `CREATE TABLE USERS (
      id VARCHAR2(64) PRIMARY KEY,
      user_id VARCHAR2(64),
      username VARCHAR2(50),
      email VARCHAR2(255) NOT NULL UNIQUE,
      password_hash VARCHAR2(255) NOT NULL,
      full_name VARCHAR2(150),
      role VARCHAR2(20) DEFAULT 'USER' NOT NULL,
      refresh_token_hash VARCHAR2(255),
      is_active NUMBER(1) DEFAULT 1 NOT NULL,
      failed_login_attempts NUMBER DEFAULT 0 NOT NULL,
      locked_until TIMESTAMP WITH TIME ZONE,
      last_login TIMESTAMP WITH TIME ZONE,
      last_login_at TIMESTAMP WITH TIME ZONE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE CAMERAS (
      id VARCHAR2(64) PRIMARY KEY,
      camera_id NUMBER,
      user_id VARCHAR2(64) DEFAULT 'default',
      name VARCHAR2(100) NOT NULL,
      camera_name VARCHAR2(100),
      location VARCHAR2(150),
      camera_location VARCHAR2(150),
      protocol VARCHAR2(50) DEFAULT 'RTSP',
      source_type VARCHAR2(50) DEFAULT 'RTSP',
      camera_source VARCHAR2(500),
      source_uri_encrypted VARCHAR2(500),
      rtsp_url_encrypted VARCHAR2(500),
      enabled NUMBER(1) DEFAULT 1 NOT NULL,
      priority NUMBER DEFAULT 1 NOT NULL,
      calibration_id VARCHAR2(64),
      status VARCHAR2(20) DEFAULT 'ONLINE' NOT NULL,
      capabilities VARCHAR2(1000),
      ptz_enabled NUMBER(1) DEFAULT 0 NOT NULL,
      device_index NUMBER,
      last_connected_at TIMESTAMP WITH TIME ZONE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE VIDEOS (
      id VARCHAR2(64) PRIMARY KEY,
      user_id VARCHAR2(64) NOT NULL,
      original_filename VARCHAR2(255),
      file_name VARCHAR2(255),
      storage_path VARCHAR2(500) NOT NULL,
      mime_type VARCHAR2(100) DEFAULT 'video/mp4',
      file_size_bytes NUMBER NOT NULL,
      duration_seconds NUMBER DEFAULT 0,
      frame_rate NUMBER DEFAULT 30,
      resolution VARCHAR2(50),
      status VARCHAR2(20) DEFAULT 'UPLOADED' NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE SEARCH_SESSIONS (
      id VARCHAR2(64) PRIMARY KEY,
      user_id VARCHAR2(64) NOT NULL,
      object_name VARCHAR2(100) NOT NULL,
      description VARCHAR2(500),
      source_type VARCHAR2(20) NOT NULL,
      source_id VARCHAR2(100) NOT NULL,
      status VARCHAR2(50) DEFAULT 'QUEUED' NOT NULL,
      progress_percent NUMBER DEFAULT 0 NOT NULL,
      started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      completed_at TIMESTAMP WITH TIME ZONE,
      error_message VARCHAR2(500)
  )`,
  `CREATE TABLE SEARCH_EVENTS (
      id VARCHAR2(64) PRIMARY KEY,
      search_id VARCHAR2(64) NOT NULL,
      stage VARCHAR2(50) NOT NULL,
      progress NUMBER NOT NULL,
      message VARCHAR2(500) NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE DETECTION_RESULTS (
      id VARCHAR2(64) PRIMARY KEY,
      search_id VARCHAR2(64) NOT NULL,
      found NUMBER(1) NOT NULL,
      confidence NUMBER(5, 2) NOT NULL,
      detected_label VARCHAR2(100) NOT NULL,
      dominant_color VARCHAR2(50),
      color_confidence NUMBER(5, 2),
      secondary_colors_json VARCHAR2(1000),
      frame_timestamp_ms NUMBER,
      evidence_frame_path VARCHAR2(500),
      bounding_box_json VARCHAR2(1000),
      track_id NUMBER,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE DETECTIONS (
      id VARCHAR2(64) PRIMARY KEY,
      detection_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
      user_id VARCHAR2(64),
      search_id VARCHAR2(64),
      camera_id VARCHAR2(64),
      object_name VARCHAR2(100),
      confidence NUMBER(5, 2),
      timestamp_seconds NUMBER,
      video_timestamp VARCHAR2(20),
      frame_number NUMBER,
      bounding_box_x NUMBER,
      bounding_box_y NUMBER,
      bounding_box_width NUMBER,
      bounding_box_height NUMBER,
      detection_status VARCHAR2(50),
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE OBJECT_TRACKS (
      id VARCHAR2(64) PRIMARY KEY,
      search_id VARCHAR2(64) NOT NULL,
      track_id NUMBER NOT NULL,
      class_name VARCHAR2(100) NOT NULL,
      confidence NUMBER(5, 2) NOT NULL,
      frame_index NUMBER NOT NULL,
      timestamp_ms NUMBER NOT NULL,
      bbox_x NUMBER NOT NULL,
      bbox_y NUMBER NOT NULL,
      bbox_width NUMBER NOT NULL,
      bbox_height NUMBER NOT NULL,
      status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
      last_seen TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE SEARCH_RESULTS (
      id VARCHAR2(64) PRIMARY KEY,
      search_id VARCHAR2(64) NOT NULL,
      target_name VARCHAR2(100) NOT NULL,
      target_found NUMBER(1) NOT NULL,
      final_confidence NUMBER(5, 2) NOT NULL,
      detection_id VARCHAR2(64),
      matched_track_id NUMBER,
      summary_notes VARCHAR2(1000),
      last_seen_timestamp NUMBER,
      last_seen_frame NUMBER,
      last_seen_bbox VARCHAR2(1000),
      last_seen_confidence NUMBER(5, 2),
      last_seen_color VARCHAR2(50),
      last_seen_evidence_path VARCHAR2(500),
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE EVIDENCE_FILES (
      id VARCHAR2(64) PRIMARY KEY,
      session_id VARCHAR2(64) NOT NULL,
      detection_id VARCHAR2(64),
      track_id NUMBER,
      video_id VARCHAR2(64),
      frame_number NUMBER NOT NULL,
      timestamp_ms NUMBER NOT NULL,
      original_image_path VARCHAR2(500) NOT NULL,
      annotated_image_path VARCHAR2(500),
      selection_policy VARCHAR2(50) DEFAULT 'highest_confidence',
      confidence NUMBER(5, 2),
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE AUDIT_LOGS (
      id VARCHAR2(64) PRIMARY KEY,
      user_id VARCHAR2(64),
      action VARCHAR2(100) NOT NULL,
      resource_type VARCHAR2(50) NOT NULL,
      resource_id VARCHAR2(64),
      ip_address VARCHAR2(50),
      user_agent VARCHAR2(255),
      request_id VARCHAR2(64),
      status VARCHAR2(20) NOT NULL,
      details_json VARCHAR2(2000),
      previous_hash VARCHAR2(64),
      current_hash VARCHAR2(64),
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE SEARCH_JOBS (
      id VARCHAR2(64) PRIMARY KEY,
      session_id VARCHAR2(64),
      search_id VARCHAR2(64),
      camera_id VARCHAR2(64) NOT NULL,
      job_status VARCHAR2(50) DEFAULT 'INITIALIZING' NOT NULL,
      target_found NUMBER(1) DEFAULT 0 NOT NULL,
      confidence NUMBER(5, 2) DEFAULT 0 NOT NULL,
      frames_processed NUMBER DEFAULT 0 NOT NULL,
      elapsed_seconds NUMBER DEFAULT 0 NOT NULL,
      error_message VARCHAR2(1000),
      started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      ended_at TIMESTAMP WITH TIME ZONE,
      last_frame_at TIMESTAMP WITH TIME ZONE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE SEARCH_TARGETS (
      id VARCHAR2(64) PRIMARY KEY,
      search_id VARCHAR2(64) NOT NULL,
      label VARCHAR2(100) NOT NULL,
      color VARCHAR2(50),
      priority NUMBER DEFAULT 1 NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE CAMERA_CALIBRATIONS (
      id VARCHAR2(64) PRIMARY KEY,
      camera_id VARCHAR2(64) NOT NULL,
      calib_json VARCHAR2(4000) NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE CAMERA_STREAM_STATUS (
      id VARCHAR2(64) PRIMARY KEY,
      camera_id VARCHAR2(64) NOT NULL,
      status VARCHAR2(50) NOT NULL,
      fps NUMBER,
      bitrate NUMBER,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`
];

async function main() {
  const user = process.env.ORACLE_USER || 'system';
  const password = process.env.ORACLE_PASSWORD || 'system';
  const connectString = process.env.ORACLE_CONNECTION_STRING || `${process.env.ORACLE_HOST || 'localhost'}:${process.env.ORACLE_PORT || 1521}/${process.env.ORACLE_SERVICE_NAME || 'XEPDB1'}`;

  console.log(`Connecting to Oracle as ${user} at ${connectString}...`);
  const conn = await oracledb.getConnection({ user, password, connectString });
  console.log('Connected successfully!');

  // Ensure USERS has ID column
  try {
    const cols = await conn.execute("SELECT column_name FROM user_tab_columns WHERE table_name = 'USERS'");
    const names = (cols.rows || []).map((r) => r[0]);
    if (names.length > 0 && !names.includes('ID')) {
      console.log('Old USERS table found without ID column. Dropping to recreate...');
      await conn.execute('DROP TABLE USERS CASCADE CONSTRAINTS PURGE');
    }
  } catch {}

  // Ensure VIDEOS has RESOLUTION column
  try {
    const cols = await conn.execute("SELECT column_name FROM user_tab_columns WHERE table_name = 'VIDEOS'");
    const names = (cols.rows || []).map((r) => r[0]);
    if (names.length > 0 && !names.includes('RESOLUTION')) {
      console.log('Old VIDEOS table found without RESOLUTION column. Dropping to recreate...');
      await conn.execute('DROP TABLE VIDEOS CASCADE CONSTRAINTS PURGE');
    }
  } catch {}

  // Ensure CAMERAS has PROTOCOL column
  try {
    const cols = await conn.execute("SELECT column_name FROM user_tab_columns WHERE table_name = 'CAMERAS'");
    const names = (cols.rows || []).map((r) => r[0]);
    if (names.length > 0 && !names.includes('PROTOCOL')) {
      console.log('Old CAMERAS table found without PROTOCOL column. Dropping to recreate...');
      await conn.execute('DROP TABLE CAMERAS CASCADE CONSTRAINTS PURGE');
    }
  } catch {}

  for (const sql of ddl) {
    const match = sql.match(/CREATE TABLE ([A-Z_]+)/);
    const tableName = match ? match[1] : 'TABLE';
    try {
      await conn.execute(sql);
      console.log(`[SUCCESS] Created table: ${tableName}`);
    } catch (err) {
      if (err.errorNum === 955) {
        console.log(`[EXISTS] Table ${tableName} already exists.`);
      } else {
        console.error(`[ERROR] Failed to create ${tableName}: ${err.message}`);
      }
    }
  }

  await conn.close();
  console.log('Done initializing CTRLF2 Oracle tables!');
}

main().catch((err) => {
  console.error('Fatal initialization error:', err);
  process.exit(1);
});
